name: Build and Release

on:
  push:
    branches: [ "main", "master" ]

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Build Executable
      shell: cmd
      run: |
        build.bat

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: latest
        name: Latest Release
        files: dfu_helper.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
